/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const translations = {
  en: { nav: { about: 'About', skills: 'Skills', projects: 'Projects', training: 'Training', certificates: 'Certificates', language: 'Language' }, hero: { greeting: 'Hello, I’m', role: 'Software Developer | C++ • C# • SQL', description: 'Computer Engineering student at Selçuk University, with a strong specialization in C++, C#, and SQL/SQL Server, built through intensive structured training and hands-on project development. I have designed and built multiple structured software systems — including pharmacy management, point-of-sale, and banking applications — applying layered architecture and solid software design principles across the full development lifecycle. I am continuously expanding my technical range while maintaining a deep foundation in the fundamentals of software engineering.', focusLabel: 'CURRENTLY FOCUSED ON', focus: 'Building with intent.' }, headings: { about: 'What My Development Experience Includes', skills: 'My Technical Stack & Foundations', featured: 'Featured Projects', other: 'Other Projects', education: 'Education', training: 'Training & Professional Development', achievements: 'Achievements & Certifications' }, common: { viewRepository: 'View Repository', viewCertificate: 'View Certificate', course: 'Course', certificatesIntro: 'Certificates obtained for the completed courses within the structured programming and software development training path.', completed: 'Completed', upcoming: 'Upcoming', currentStudent: 'Current Student', currentlyPursuing: 'CURRENTLY PURSUING' } },
  tr: { nav: { about: 'Hakkımda', skills: 'Yetenekler', projects: 'Projeler', training: 'Eğitim', certificates: 'Sertifikalar', language: 'Dil' }, hero: { greeting: 'Merhaba, ben', role: 'Yazılım Geliştirici | C++ • C# • SQL', description: 'Selçuk Üniversitesi Bilgisayar Mühendisliği öğrencisiyim. Yoğun ve yapılandırılmış eğitim ile uygulamalı proje geliştirme sayesinde C++, C# ve SQL/SQL Server alanlarında güçlü bir uzmanlık kazandım. Eczane yönetimi, satış noktası ve bankacılık uygulamaları dahil olmak üzere katmanlı mimari ve sağlam yazılım tasarım ilkelerini kullanarak çeşitli yazılım sistemleri tasarladım ve geliştirdim. Yazılım mühendisliğinin temellerindeki derin altyapımı korurken teknik yetkinliklerimi sürekli genişletiyorum.', focusLabel: 'ŞU ANDA ODAKLANDIĞIM', focus: 'Amaçla geliştirmek.' }, headings: { about: 'Geliştirme Deneyimim Neleri Kapsıyor', skills: 'Teknik Altyapım ve Temellerim', featured: 'Öne Çıkan Projeler', other: 'Diğer Projeler', education: 'Eğitim', training: 'Eğitim ve Profesyonel Gelişim', achievements: 'Başarılar ve Sertifikalar' }, common: { viewRepository: 'Depoyu Görüntüle', viewCertificate: 'Sertifikayı Görüntüle', course: 'Kurs', certificatesIntro: 'Yapılandırılmış programlama ve yazılım geliştirme eğitim yolundaki tamamlanmış kurslar için alınan sertifikalar.', completed: 'Tamamlandı', upcoming: 'Yaklaşan', currentStudent: 'Mevcut Öğrenci', currentlyPursuing: 'HALEN DEVAM EDİYOR' } },
  ar: { nav: { about: 'عني', skills: 'المهارات', projects: 'المشاريع', training: 'التدريب', certificates: 'الشهادات', language: 'اللغة' }, hero: { greeting: 'مرحبًا، أنا', role: 'مطوّر برمجيات | C++ • C# • SQL', description: 'أنا طالب هندسة حاسوب في جامعة سلجوق، مع تخصص قوي في C++ وC# وSQL/SQL Server، اكتسبته من خلال تدريب مكثف ومنهجي وتطوير مشاريع عملية. صممت وبنيت عدة أنظمة برمجية منظمة، منها إدارة الصيدليات ونقاط البيع والتطبيقات المصرفية، مع تطبيق المعمارية الطبقية ومبادئ تصميم البرمجيات السليمة خلال دورة التطوير الكاملة. أواصل توسيع نطاقي التقني مع الحفاظ على أساس عميق في مبادئ هندسة البرمجيات.', focusLabel: 'أركز حاليًا على', focus: 'البناء بهدف واضح.' }, headings: { about: 'ما تتضمنه خبرتي في التطوير', skills: 'بنيتي التقنية وأساسياتي', featured: 'المشاريع المميزة', other: 'مشاريع أخرى', education: 'التعليم', training: 'التدريب والتطوير المهني', achievements: 'الإنجازات والشهادات' }, common: { viewRepository: 'عرض المستودع', viewCertificate: 'عرض الشهادة', course: 'الدورة', certificatesIntro: 'شهادات تم الحصول عليها للدورات المكتملة ضمن مسار التدريب المنهجي في البرمجة وتطوير البرمجيات.', completed: 'مكتمل', upcoming: 'قادم', currentStudent: 'طالب حالي', currentlyPursuing: 'أدرس حاليًا' } },
}
const LanguageContext = createContext(null)
export function LanguageProvider({ children }) { const [language, setLanguage] = useState(() => localStorage.getItem('portfolio-language') || 'en'); useEffect(() => { localStorage.setItem('portfolio-language', language); document.documentElement.lang = language; document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr' }, [language]); const value = useMemo(() => ({ language, setLanguage, t: translations[language] }), [language]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider> }
export function useLanguage() { const context = useContext(LanguageContext); if (!context) throw new Error('useLanguage must be used within LanguageProvider'); return context }
